### ISSUE TITLE
Problem with maven dependency

### ISSUE THREAD

**Issue by ashfaq92** [stepstone-tech/hnswlib-jna#4]
when i try to add this dependency in my POM.xml
<dependency>
            <groupId>com.stepstone.search.hnswlib.jna</groupId>
            <artifactId>hnswlib-jna</artifactId>
            <version>1.1.1</version>
        </dependency>

I get this error:
Dependency 'com.stepstone.search.hnswlib.jna.hnswlib-jna:1.1.1' not found.

I manually tried to search [maven repo](https://mvnrepository.com/), but it was not found there too.

**Comment by ashfaq92** [comment]
Besides, if maven dependency does not exist, please update your examples file by using `.dll` file. What is a proper way to access `.dll` file using JNA?

In other words, please update your documentation. For newbies, like me, it is difficult set the project up and running. For example, your example file assumes that user has preset the maven dependency, but dependency is not found. In your readme, file, compiling and converting to `.dll` is explained but in examples it is not explained how to use that `dll`.

**Comment by hussamaa** [comment]
Hi @ashfaq92,

I'd guess, you're trying to use it on Windows. If you use Windows 10, you can install visual studio 2019 and skip the step of compiling the DLL (https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019), which will make things much easier for you.

> when i try to add this dependency in my POM.xml

Indeed, the library has not been published on maven central. I'd suggest you to clone the repo and run: "mvn install -DskipTests" on the directory. It should generate the jars on you ~/.m2 folder which will enable you to use the project as a dependency like you tried. Otherwise, you can also use the .jar in the release which contain all the dependencies. 

>  it is difficult set the project up and running.

The example project should be your way to go. Please after cloning and running mvn to install the jars, import the project on a IDEA (I use Intellij) and then If you navigate to the hwnslib-jna-example you will see an **App.java**, which contains the examples. If you run that class, you should see execution, working fine using the library. If you have problems with dependencies, please check the pom.xml of the example project and rename the dependency from **hnswlib-jna-legacy** to **hnswlib-jna** and it should be fine.

Let's go step by step. We can use this thread as support. Let me know how it goes. 

BR,
Hussama

![Screenshot 2020-06-29 at 09 56 07](https://user-images.githubusercontent.com/5069111/85988604-936df280-b9ef-11ea-8157-5a022df7f74f.png)
![Screenshot 2020-06-29 at 09 58 28](https://user-images.githubusercontent.com/5069111/85988610-949f1f80-b9ef-11ea-8152-7d38bb7992ce.png)
![Screenshot 2020-06-29 at 10 01 12](https://user-images.githubusercontent.com/5069111/85988613-95d04c80-b9ef-11ea-9eb1-7fe1e9aba067.png)

**Comment by ashfaq92** [comment]
i have run the command `mvn install -DskipTests` with following result:
![image](https://user-images.githubusercontent.com/28701122/85991166-a3082e00-ba25-11ea-8ea3-284f5373bf21.png)

But still, I can't run App.java. following errors are shown:
![image](https://user-images.githubusercontent.com/28701122/85991246-c632dd80-ba25-11ea-91c9-14ea3a55d981.png)

**Comment by ashfaq92** [comment]
Thanks for prompt reply. I followed your commands, all errors seem to be gone. But, when I run App.java, I get following error:

`Exception in thread "main" java.lang.UnsatisfiedLinkError: It's not possible to use the pre-generated dynamic libraries on your system. Please compile it yourself (if not done yet) and set the "jna.library.path" property with correct path to where "libhnswlib-jna.dll" is located.`


![image](https://user-images.githubusercontent.com/28701122/85991612-435e5280-ba26-11ea-82d9-a8b4e8e90831.png)

**Comment by hussamaa** [comment]
Thanks for your feedback. We are almost there. Have you installed the Visual Studio Tools already? 

If yes, could you please just try commenting out these lines that are in the main method and running it again?

```
File projectFolder = new File("hnswlib-jna-example/lib");  
System.setProperty("jna.library.path", projectFolder.getAbsolutePath());
```

When these lines aren't specified, the library tries to use the the pre-compiled libraries (which should be fine for Win10 + VS2019).

**Comment by ashfaq92** [comment]
So, it's been whole day =D. If i try to comment those lines of code that you mentioned, I get new error:
![image](https://user-images.githubusercontent.com/28701122/86018330-c9df5800-ba57-11ea-8c8b-43e7e3008fd9.png)

I tried to install all packages and tools of visual studio. please check following image. but still same error is repeated that i mentioned above. 

![image](https://user-images.githubusercontent.com/28701122/86018388-db286480-ba57-11ea-98c4-2fde0ac2e531.png)

![image](https://user-images.githubusercontent.com/28701122/86018415-e67b9000-ba57-11ea-8545-d3f7b50ede98.png)


NOTE: please there are plenty of Visual Studio Tools bundelled and they take Gigabytes of storage. Hence, you should EXACTLY specify what tools and packages to download. There is also an option of `import configuration` in visual studio tools. So if you send here you exported configuration file, maybe importing that file in our visual studio tools will give us the exact tools and packages that you have
![image](https://user-images.githubusercontent.com/28701122/86018754-5be76080-ba58-11ea-8214-24f0b3d5f9cc.png)

**Comment by hussamaa** [comment]
@ashfaq92, thanks for your feedback once again. I'm writing all the points down to improve our documentation. :D 

Yes, you installed the correct package, VS Build Tools 2019 (C++ build tools). I'm now puzzled with the NullPointer. It looks like there is something wrong happening when we copy the libs into your temp folder. Sorry, I don't have an environment with Win10 available right now to double check it for you but I hope to get back with the correct fix soon.

In meanwhile, what came in my mind and that you can try is:
1) Copy all the files from **hnswlib-jna/src/main/resources/** to **hnswlib-jna-example/lib/** (the files are: libhnswlib-jna.*)
2) Put the lines we commented out back [remove the comments] (File projectFolder....)
3) Run it again and it should 🚀 .

![Screenshot 2020-06-29 at 16 51 23](https://user-images.githubusercontent.com/5069111/86020937-d5fff100-ba28-11ea-961b-0401d2404bd8.png)

Otherwise, I don't know how familiar you are with Java, but you could put a breakpoint on HnswlibFactory::checkIfLibraryProvidedNeedsToBeLoadedIntoSO to debug and found the cause. Feel free to modify the code. You're also welcome to open a PR with your changes.

Thanks a lot,
Hussama

**Comment by ashfaq92** [comment]
Hi @hussamaa thank you so much for your cooperation. Manually copying files into `lib` folder did the trick. Now it is working fine. 
If everything will go fine, your repo will be mentioned and credited in my upcoming research paper :)   
Surely, I shall try to do my best to improve and simplify the project with PRs if I could. By the way, the project can be simplified in a number of ways:
1. Publishing dependency to `maven repository` (the command `mvn install -DskipTests` works but it is not intuitive)
2. Already placing JNA files in **lib** folder
3. Chosing one simple method of setting up and working the the project (right now, there are multiple confusing options i.e. using jar, using dependency, compiling using build tools)

**Comment by hussamaa** [comment]
Wow! Good news! Indeed. Tomorrow we reserved a slot to work on publishing the jars on maven central (we should have done that before, sorry). It will make life easier for everyone. I hope to push some of your comments already on the next version.

Indeed, the step of compiling the native library can be a bit tricky (requires tooling, compilers options and it is a bit error prone). That was one of the reasons we provided some "pre-compiled" shared libraries, which makes things a little bit more abstract for the users and other teams. However, it can still fail depending on the o.s. version. 

Let me know if you have issues, I'd be happy to give a hand.

BR,
Hussama

**Comment by hussamaa** [comment]
Hi @ashfaq92,

We released v1.2.0 which includes the latest Hwnslib v0.4.0, the setEf method and the fix for the loading the pre-generated library on Windows 10, together with some updates on documentation and examples. It is also published on maven repo and it should be easier for you to integrate. 

https://repo1.maven.org/maven2/com/stepstone/search/hnswlib/jna/hnswlib-jna/1.2.0/

Could you please check it out? Also, please Let me know if you have any issue or problem and I'd be happy to have a look. 

BR,
Hussama

**Comment by ashfaq92** [comment]
Thank you so much for dedication and guidance. I shall integrate it into my project and hope for some interesting findings

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ashfaq92** [comment]
With the new version `1.2.0` maven dependency problem is successfully solved.
